### ISSUE TITLE
CSS för event-flöde på startsidan

### ISSUE THREAD

**Issue by philipohlund** [thejool/systemvetenskap.nu#5]
Det ligger något "scrollmagic" för den blåa rubriken för event på startsidan. Detta resulterar i att event-rubriken "scrollar med" en liten bit som _position:fixed_ innan den stannar lite längre ner som _position:relative_ med lite _margin_ mot bannern (se screenshot nedan).
![skarmavbild 2017-09-03 kl 16 40 00](https://user-images.githubusercontent.com/26908455/30003955-8d65a77a-90c6-11e7-9c3b-693c1768daaf.png)
Förslagsvis tar vi bort hela denna funktion och bara lägger den i en fast position direkt under bannern.

**Comment by sandstreampop** [comment]
Ska vara löst i och med min pull request idag!
