### ISSUE TITLE
Fixa kategori-sortering på flöden

### ISSUE THREAD

**Issue by philipohlund** [thejool/systemvetenskap.nu#8]
Just nu är det en loop som bara hämtar de kommande eventen på flödessidan (/event) oavsett om man klickat på en kategori eller inte. Förmodligen är samma problem på /nyheter, /podd och /karriar också.

**Comment by sandstreampop** [comment]
Jag och Daniel kikar på detta!

**Comment by sandstreampop** [comment]
Ska vara fixat i och med Daniels pull request 5/9-17
